### ISSUE TITLE
Grappling Hook: Restitched 1.20(.1)-v1.7 - Attempting to mine grapplemod:block_grapple_modifier just destroys the block and upgrades

### ISSUE THREAD

**Issue by rxay579** [squeeglii/grapplemod-restitched#17]
## Versions:

 - The Grapple Hook Mod:  v1.7
 - Minecraft:  v1.20.1
 - Mod Loader:  Fabric Loader v0.15.7
 - Fabric API 0.92.0+1.20.1
 - Cloth Config: v11.1.118

## Description:

After placing the upgrade block, I can't find a way to pick it back up without it just breaking and disappearing with any applied upgrades being lost as well.

Noticed in a custom mod list, verified in a simple setup with just Minecraft, Fabric API, Cloth Config, and Grapple Hook Mod Restitched.

Glancing through the mod and code here on github, I don't see anything I'm familiar with that would control what or how the block is mineable.
Is there a way to pick up/move the block without other mods?

**Comment by squeeglii** [comment]
Replicated it - There was behaviour implemented in the past to drop all the upgrades & the block so that breaking is kinda odd. I think a merge may have gone wrong at some point and nuked some files.

[The code here handles drops for the upgrades when mined.](https://github.com/squeeglii/grapplemod-restitched/blob/6dea8fc58f8a0b6c539e3b1ab5de6371fce44daf/src/main/java/com/yyon/grapplinghook/block/modifierblock/GrappleModifierBlock.java#L59)

However, the datapack file for minable blocks seems to have been lost over time so I believe that's the issue. Will push a hotfix out soonish.

**Comment by squeeglii** [comment]
Patched - will push out soon-ish as v1.8

**Comment by rxay579** [comment]
If I'm reading the change correctly, the patch adds one missing 'axe.json'.
I'll try it as a datapack patch for now with the v1.7 version and await the full update.

**Comment by squeeglii** [comment]
yup, that's correct. Simple lil' fix :)
